# Generated by Django 5.2.1 on 2025-05-31 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_txt', models.CharField(max_length=3)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='Signimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signimg_img', models.CharField(max_length=10)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.label')),
            ],
        ),
    ]
