# Generated by Django 5.2 on 2025-06-19 14:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signimg',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signimg',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signimg',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signimg',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'webm', 'jif'])]),
        ),
        migrations.AlterField(
            model_name='signimg',
            name='signimg_img',
            field=models.ImageField(blank=True, null=True, upload_to='signimg_images/'),
        ),
    ]
