# Generated by Django 5.2 on 2025-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_signimg_description_signimg_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signimg',
            name='title',
            field=models.CharField(default='Sign Image', max_length=200),
        ),
    ]
