# Generated by Django 3.2.25 on 2025-06-21 12:53

from django.db import migrations
import webcampicture.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_signimg_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='signimg',
            name='detected_img',
            field=webcampicture.fields.WebcamPictureField(blank=True, null=True, upload_to='detected_images/'),
        ),
    ]
