# Generated by Django 3.2.25 on 2025-06-21 13:37

from django.db import migrations
import webcampicture.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_signimg_detected_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signimg',
            name='detected_img',
            field=webcampicture.fields.WebcamPictureField(blank=True, help_text='Image captured from webcam', null=True, upload_to='detected_images/'),
        ),
    ]
